require 'bankin/version'
require 'bankin/configuration'
require 'bankin/base'
require 'bankin/error'
require 'bankin/resource'
require 'bankin/collection'

require 'bankin/resources/bank'
require 'bankin/resources/user'
require 'bankin/resources/item'
require 'bankin/resources/account'
require 'bankin/resources/transaction'
require 'bankin/resources/category'
